[workspace]
members = [
    "shotover-proxy",
    "test-helpers",
    "cqlparser"
]

# https://deterministic.space/high-performance-rust.html
[profile.release]
lto = "fat"
codegen-units = 1

[profile.bench]
lto = "fat"
codegen-units = 1
