[package]
name = "website"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
subprocess.workspace = true
anyhow.workspace = true
rinja = "0.3.5"
semver = "1.0.23"
devserver_lib = { version = "0.4.2", default-features = false }
clap.workspace = true