[book]
authors = ["Shotover Team"]
language = "en"
multilingual = false
src = "src"
title = "Shotover"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.linkcheck]
# Should we check links on the internet? Enabling this option adds a
# non-negligible performance impact
follow-web-links = false

warning-policy = "error"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
